language: ruby
dist: precise
sudo: required
rvm:
  - 2.1.9
  # Ruby with Puppet 5
  - 2.4.4
notifications:
  email:
   - raphael.pinson@camptocamp.com
env:
# base env
  # Test Puppet 4
  - PUPPET=4.0 RUBY_AUGEAS=0.5
  # Test Oldest Puppet, Inc. supported Puppet
  - PUPPET=4.10.4 RUBY_AUGEAS=0.5 FORGE_PUBLISH=true
  # Test latest Puppet version
  - PUPPET=5.5 RUBY_AUGEAS=0.5

matrix:
  fast_finish: true
  exclude:
    # base exclude
    # No support for Ruby 2.1.9 in Puppet 5
    - rvm: 2.1.9
      env: PUPPET=5.5 RUBY_AUGEAS=0.5

install:
  - "travis_retry ./.travis.sh"
script:
  - AUGEAS_LENS_LIB=lib/augeas/lenses:augeas/lenses bundle exec rake
  # Do not include the augeas/ directory in the deployed module
  - rm -rf augeas/
deploy:
  provider: puppetforge
  user: herculesteam
  password:
    secure: "ctbh1VqtkZnqCWRa5YUONzS4LuJ3h36wOcn8pCyxNtdOcHNvbFYWiFaVIlgJXkkwFIRU7hnhpIXZ9bRCLqmvz3awVzc7baThgx2Asi5jkMlltXWIuCt8ZPHHpLNSEa0zHY88o7LUqTuvUCbG3EINYoA7o6ShBUV5vJ8UE6IesqU="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.1.9
    condition: "$FORGE_PUBLISH = true"
